### ISSUE TITLE
Sending a Message Does Not Require a Database Read

### ISSUE THREAD

**Issue by nmh6z** [ajmaln/DRF-Chat#7]
Hi,

We have a project that uses this code as a base for instant messaging. We have added to it though so that we can filter messages for profanity and send images. We noticed that when we go to send a message that no database read is required. This causes an issue where profanity isn't filtered and messages are not displayed until the page is refreshed. We were wondering if you knew how to get sending to also require a database read. 

Thanks,

**Comment by ajmaln** [comment]
Hi sorry for the late reply. I was a bit busy.

When you send a message, database read is required only at the receiver end. I thought this would be easy to implement since the sender side already have the message.

But if you want a database read at the sender side too, you could do it with some JavaScript code in the frontend, that would result in a database read even in the sender side only which will help you apply the profanity filter in sender side also.
